version: "3"
services:
  mujin-open-challenge:
    image: swang095/mujinopenchallenge:v5
    container_name: mujin-open-challenge
    hostname: "opcua_gateway_server"
    network_mode: host
    ports:
      - 5000:5000
    working_dir: "/workspaces/mujin-open-challenge"
    privileged: true
    stdin_open: true
    tty: true
    restart: always
    entrypoint: bash /workspaces/mujin-open-challenge/entrypoint.sh
    environment:
      - CONTAINER_NAME=mujin-open-challenge
